
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy-engine
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: proxy-engine
  template:
    metadata:
      labels:
        app: proxy-engine
    spec:
      containers:
        - name: proxy-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-proxy-engine-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
