
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-anomaly-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: anomaly-service
  template:
    metadata:
      labels:
        app: anomaly-service
    spec:
      containers:
        - name: anomaly-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-anomaly-service-config
