"""Add agent_behavioral_profiles

Revision ID: 65ae18fbf1bc
Revises: 7035ff8df250
Create Date: 2026-07-26 09:48:25.423691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65ae18fbf1bc'
down_revision: Union[str, None] = '7035ff8df250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_behavioral_profiles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('profile_period_start', sa.DateTime(), nullable=False),
    sa.Column('profile_period_end', sa.DateTime(), nullable=False),
    sa.Column('tool_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_content_length_bytes', sa.Float(), nullable=True),
    sa.Column('stddev_content_length_bytes', sa.Float(), nullable=True),
    sa.Column('avg_calls_per_session', sa.Float(), nullable=True),
    sa.Column('typical_session_duration_minutes', sa.Float(), nullable=True),
    sa.Column('hourly_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('is_stable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_behavioral_profiles')
    # ### end Alembic commands ###
