"""Add tenant_policies

Revision ID: 7035ff8df250
Revises: 73ddeddf9c2d
Create Date: 2026-07-26 09:13:50.845592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7035ff8df250'
down_revision: Union[str, None] = '73ddeddf9c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_overview_metrics')
    op.add_column('tenant_policies', sa.Column('sleeper_age_threshold_days', sa.Integer(), nullable=True))
    op.add_column('tenant_policies', sa.Column('sleeper_reference_spike_threshold', sa.Integer(), nullable=True))
    op.add_column('tenant_policies', sa.Column('sleeper_trust_ceiling', sa.Float(), nullable=True))
    op.add_column('tenant_policies', sa.Column('alert_webhook_url', sa.String(length=255), nullable=True))
    op.add_column('tenant_policies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tenant_policies', 'tenant_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'tenant_pro_1'::character varying"))
    op.alter_column('tenant_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'tenant_policies', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('tenant_policies', 'id')
    op.drop_column('tenant_policies', 'rule_value')
    op.drop_column('tenant_policies', 'rule_type')
    op.drop_column('tenant_policies', 'enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_policies', sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('tenant_policies', sa.Column('rule_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tenant_policies', sa.Column('rule_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('tenant_policies', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_policies', type_='foreignkey')
    op.alter_column('tenant_policies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tenant_policies', 'tenant_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("'tenant_pro_1'::character varying"))
    op.drop_column('tenant_policies', 'updated_at')
    op.drop_column('tenant_policies', 'alert_webhook_url')
    op.drop_column('tenant_policies', 'sleeper_trust_ceiling')
    op.drop_column('tenant_policies', 'sleeper_reference_spike_threshold')
    op.drop_column('tenant_policies', 'sleeper_age_threshold_days')
    op.create_table('system_overview_metrics',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('shielded_requests', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('blocked_threats', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('high_severity_injections', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('enforced_policies', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=False),
    sa.Column('total_policies', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('3.8'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_overview_metrics_pkey'))
    )
    # ### end Alembic commands ###
