"""Add compliance_reports

Revision ID: 73ddeddf9c2d
Revises: 005_usage_counters
Create Date: 2026-07-25 19:58:33.357760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73ddeddf9c2d'
down_revision: Union[str, None] = '005_usage_counters'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('report_hash', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('regulatory_frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('system_overview_metrics')
    op.alter_column('usage_counters', 'reported',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_counters', 'reported',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('system_overview_metrics',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('shielded_requests', sa.BIGINT(), server_default=sa.text('4892104'), autoincrement=False, nullable=False),
    sa.Column('blocked_threats', sa.BIGINT(), server_default=sa.text('1284'), autoincrement=False, nullable=False),
    sa.Column('high_severity_injections', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False),
    sa.Column('enforced_policies', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=False),
    sa.Column('total_policies', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('3.8'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_overview_metrics_pkey'))
    )
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###
