
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-healing-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: healing-worker
  template:
    metadata:
      labels:
        app: healing-worker
    spec:
      containers:
        - name: healing-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-healing-worker-config
